# Generated by Django 4.2 on 2023-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nfc_iDm', models.CharField(max_length=100, unique=True)),
                ('last_touch_time', models.DateTimeField()),
                ('is_always_visible', models.BooleanField(default=False)),
            ],
        ),
    ]
