# Generated by Django 4.2 on 2023-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekenGK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='discord_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
