# Generated by Django 4.2 on 2023-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekenGK', '0002_message_userdata_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='last_touch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
