# Generated by Django 4.2 on 2023-04-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekenGK', '0003_alter_userdata_last_touch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='version_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='discord_id',
            field=models.IntegerField(default=-1),
        ),
    ]
