# Generated by Django 4.2 on 2023-04-27 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekenGK', '0005_rename_discord_id_message_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='register_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
