# Generated by Django 4.2 on 2023-04-27 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekenGK', '0006_userdata_is_temporary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='discord_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_touch_time',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
